platform :ios, '13.0'

target 'CryptoApp' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for CryptoApp

  pod 'FacebookCore', '~> 0.9.0'
  pod 'FacebookLogin', '~> 0.9.0'
  pod 'FacebookShare', '~> 0.9.0'

  pod 'Firebase/Core', '~> 6.11.0'
  pod 'Firebase/Auth', '~> 6.11.0'
  pod 'Firebase/Database', '~> 6.11.0'
  pod 'Firebase/Storage', '~> 6.11.0'
  pod 'Firebase/Firestore', '~> 6.11.0'
  pod 'Firebase/Messaging', '~> 6.11.0'

  pod 'Kingfisher', '~> 5.9.0'

  pod 'Charts', '~> 3.4.0'
  pod 'ChameleonFramework', '~> 2.1.0'

end
